title: @mNakamoto
author:
  name: Mirek Nakamoto
  email: mirek.nakamoto@yandex.com
description: > # this means to ignore newlines until "show_excerpts:"
 Quasi-Anonymous Cyberpunk, Hacker, Freedom and Free Speach Activist. Bastard son of Satoshi - the author of Bitcoin. 
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  mireknakamoto
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
    # google_scholar_id: qc6CJjYAAAAJ

    # Mastodon instances
    mastodon:
    - username: mirekNakamoto
      instance: mastodon.online
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    gitlab:
    - username: mirekNakamoto
      instance: gitlab.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

kramdown:
  math_engine: katex

# Build settings
remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
